apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: app
        image: 847370586410.dkr.ecr.us-west-2.amazonaws.com/app_modernization/ecr_repo:4441ddda1bb673595aff823533460a560eac0234
        ports:
        - containerPort: 80