name: Java CI with Maven
on:
  #Triggers the workflow on push or pull request events but only for the master branch
  # .
  push:
    branches: [master]
jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file maven/pom.xml

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Login to ECR
      run: |
        sudo docker login docker.io -u ts2410 -p admin@123
        sudo aws ecr get-login-password --region us-west-2 | sudo docker login --username AWS --password-stdin 410398157274.dkr.ecr.us-west-2.amazonaws.com
        
    - name: Build & PUSH TO ECR
      run: |
        sudo docker build -t app_modernization/ecr_repo maven/.
        sudo docker tag app_modernization/ecr_repo:latest 410398157274.dkr.ecr.us-west-2.amazonaws.com/app_modernization/ecr_repo:latest
        sudo docker push 410398157274.dkr.ecr.us-west-2.amazonaws.com/app_modernization/ecr_repo:latest
      
      
    
    
    
